networks:
  pickside-network:
    external: true

services:
  notifsvc:
    image: thenoobgrammer/pickside-service:notification-service-latest
    container_name: notifsvc
    ports:
      - "8084:8084"
    networks:
      - pickside-network
    environment:
      - VAULT_ADDRESS=https://vault.morpheglus.org
      - VAULT_TOKEN=${VAULT_TOKEN}